name: Deploy to GitHub Pages

on:
  push:
    branches:
      - feat/alketab-search-integration-10

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get
          cd example && flutter pub get

      - name: Build Web
        run: |
          cd example
          flutter build web --release --base-href="/mushaf-imad-flutter/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web
